openapi: 3.0.0
info:
  title: Fishing predictor API
  version: 1.0.0
servers:
- url: "https://tjds2xlbe2.execute-api.us-west-2.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: "production"
paths:
  /predictions:
    get:
      summary: Get Predictions
      description: Returns a list of predictions in JSON format.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/prediction"
        '500':
          description: Internal Server Error
          content:
            application/json:
              example:
                error: "Internal Server Error"
      # You can add parameters, security, etc. as needed
      security:
      - FishingForecast: []
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-west-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-2:074935645950:function:FishingPredictionGetAPI/invocations"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        contentHandling: "CONVERT_TO_TEXT"
    options:
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
      x-amazon-apigateway-integration:
        type: "mock"
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Methods: "'OPTIONS'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
        requestTemplates:
          application/json: "{\"statusCode\": 200}"
        passthroughBehavior: "when_no_match"
components:
  securitySchemes:
    FishingForecast:
      type: "apiKey"
      name: "Authorization"
      in: "header"
      x-amazon-apigateway-authtype: "cognito_user_pools"
      x-amazon-apigateway-authorizer:
        type: "cognito_user_pools"
        providerARNs:
        - "arn:aws:cognito-idp:us-west-2:074935645950:userpool/us-west-2_RrS17PjER"
  schemas:
    prediction:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          description: Unique ID for the prediction
          example: UUID for this prediction
        date:
          type: string
          example: 07/21/2024
        location:
          type: string
          description: Name of the location
          example: Deschutes through Bend
        details:
          type: string
          description: Prediction details
          example: The Deschutes is fishing well and should continue to do so this week.  Browns and rainbows from 6-18 inches are likely
        weather:
          type: string
          description: Weather prediction
          example: Partly sunny